php-version = "8.5"

[source]
paths = [
    "app/lib",
    "01-Simple/public",
    "02-Styled/public",
    "03-Plugins/public",
    "04-Themes/public",
    "05-Autoload/src",
    "06-Session/src",
    "07-PDO/src",
    "08-Users/src",
    "09-Blog/src",
]
